### ISSUE TITLE
VRect

### ISSUE THREAD

**Issue by LubitelDeneg** [Venryx/windows-ffi#1]
I don’t understand what I'm doing wrong, I seem to have done everything according to the instructions, but I get an error:
import {VRect, CaptureScreenshot, GetForegroundWindowHandle} from "windows-ffi";
        ^^^^^
SyntaxError: The requested module 'windows-ffi' does not provide an export named 'VRect'
←[90m    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)←[39m
←[90m    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)←[39m
    at async Promise.all (index 0)
←[90m    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)←[39m
←[90m    at async loadESM (node:internal/process/esm_loader:88:5)←[39m
←[90m    at async handleMainPromise (node:internal/modules/run_main:65:12)←[39m

**Comment by Venryx** [comment]
Apologies; I seem to have forgotten to re-export the `VRect` structure (imported from my other library `js-vextensions`) out from this `windows-ffi` library.

To fix, just remove the `VRect` import from the above, and import it from `js-vextensions` instead:
```
import {VRect} from "js-vextensions";
```

In the future I may include the `Vector2` and `VRect` structures directly in `windows-ffi`, rather than importing it from my other library. (depends on how much the library gets used and such)

**Comment by LubitelDeneg** [comment]
And I'm sorry, maybe this is a mistake on my side, it's just that I'm not very good at programming, after I fixed everything, I received another error:
file:///C:/t/node_modules/windows-ffi/Dist/Manager.js:5
export let ffi = (_a = preImportConfig.ffi) !== null && _a !== void 0 ? _a : require("ffi-napi");
                                       ^

TypeError: Cannot read properties of undefined (reading 'ffi')
    at file:///C:/t/node_modules/←[4mwindows-ffi←[24m/Dist/Manager.js:5:40
←[90m    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)←[39m
    at async Promise.all (index 0)
←[90m    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)←[39m
←[90m    at async loadESM (node:internal/process/esm_loader:88:5)←[39m
←[90m    at async handleMainPromise (node:internal/modules/run_main:65:12)←[39m

**Comment by Venryx** [comment]
I think it was a mistake in my code actually; sorry about that.

To see if the cause is what I think, can you open the `YOUR_PROJECT_FOLDER/node_modules/windows-ffi/Dist/@UserSupplied/PreImportConfig.js` file (as [seen here](https://github.com/Venryx/windows-ffi/blob/master/Dist/%40UserSupplied/PreImportConfig.js)), and change this line:
```
export let preImportConfig;
```

To this?:
```
export let preImportConfig = {};
```

Then if you rebundle/rerun your program, see if the error still happens.

**Comment by LubitelDeneg** [comment]
Thanks a lot, everything works!

**Comment by Venryx** [comment]
Good to hear!

I will try to push an update to the `windows-ffi` package soon containing the fix above, so you do not have to apply the fix manually after future `npm install`s. :)

**Comment by Venryx** [comment]
FYI: Fixed both issues in `windows-ffi@0.0.4`.

**Comment by LubitelDeneg** [comment]
I'm very sorry to bother you, after the update everything works, but I would like to ask you as the developer of this package, is it possible to use require () instead of import? Because if I just remove "type": "module", and write require () instead of import, then nothing works, although many other packages work without problems.

**Comment by Venryx** [comment]
Why do you want to remove the type:module flag?

**Comment by LubitelDeneg** [comment]
I use electron in my project, and unfortunately, as I understand it, it does not support import / export, and I need to select one thing, either import or require (), and your package is the only working option with the ability to check pixels in node.js, and I need to add it to the project somehow, but require () doesn't work.
